#ifndef RANDOMIZER_CONSTANTS_H
#define RANDOMIZER_CONSTANTS_H

#include "macros.h"

#define MINOR_LOCATION_COUNT 86

#define MAX_ENERGY_CAPACITY 1299
#define MAX_MISSILE_CAPACITY 999
#define MAX_SUPER_MISSILE_CAPACITY 99
#define MAX_POWER_BOMB_CAPACITY 99

MAKE_ENUM(u8, ItemSource)
{
    /* 00 */ ITEM_SOURCE_LONG_BEAM,
    /* 01 */ ITEM_SOURCE_CHARGE_BEAM,
    /* 02 */ ITEM_SOURCE_ICE_BEAM,
    /* 03 */ ITEM_SOURCE_WAVE_BEAM,
    /* 04 */ ITEM_SOURCE_PLASMA_BEAM,
    /* 05 */ ITEM_SOURCE_BOMBS,
    /* 06 */ ITEM_SOURCE_VARIA_SUIT,
    /* 07 */ ITEM_SOURCE_GRAVITY_SUIT,
    /* 08 */ ITEM_SOURCE_MORPH_BALL,
    /* 09 */ ITEM_SOURCE_SPEED_BOOSTER,
    /* 10 */ ITEM_SOURCE_HI_JUMP,
    /* 11 */ ITEM_SOURCE_SCREW_ATTACK,
    /* 12 */ ITEM_SOURCE_SPACE_JUMP,
    /* 13 */ ITEM_SOURCE_POWER_GRIP,
    /* 14 */ ITEM_SOURCE_FULLY_POWERED,
    /* 15 */ ITEM_SOURCE_ZIPLINES,

    ITEM_SOURCE_COUNT
};

MAKE_ENUM(u8, RandoItemType) {
    /* 00 */ RIT_NONE,
    /* 01 */ RIT_ENERGY_TANK,
    /* 02 */ RIT_MISSILE_TANK,
    /* 03 */ RIT_SUPER_MISSILE_TANK,
    /* 04 */ RIT_POWER_BOMB_TANK,
    /* 05 */ RIT_MAIN_MISSILES,
    /* 06 */ RIT_MAIN_SUPER_MISSILES,
    /* 07 */ RIT_MAIN_POWER_BOMBS,
    /* 08 */ RIT_LONG_BEAM,
    /* 09 */ RIT_CHARGE_BEAM,
    /* 10 */ RIT_ICE_BEAM,
    /* 11 */ RIT_WAVE_BEAM,
    /* 12 */ RIT_PLASMA_BEAM,
    /* 13 */ RIT_BOMBS,
    /* 14 */ RIT_VARIA_SUIT,
    /* 15 */ RIT_GRAVITY_SUIT,
    /* 16 */ RIT_MORPH_BALL,
    /* 17 */ RIT_SPEED_BOOSTER,
    /* 18 */ RIT_HI_JUMP,
    /* 19 */ RIT_SCREW_ATTACK,
    /* 20 */ RIT_SPACE_JUMP,
    /* 21 */ RIT_POWER_GRIP,
    /* 22 */ RIT_SPRING_BALL,
    /* 23 */ RIT_WALL_JUMP,
    /* 24 */ RIT_INF_BOMB_JUMP,
    /* 25 */ RIT_PROGRESSIVE_JUMP, // Hi-Jump -> Space Jump
    /* 26 */ RIT_PROGRESSIVE_BOMB, // Bombs -> IBJ
    /* 27 */ RIT_FULLY_POWERED,
    /* 28 */ RIT_ZIPLINES,
    /* 29 */ RIT_ICE_TRAP,
};

// TODO: This may not be necessary
MAKE_ENUM(u8, RandoItemSprite) {
    /* 00 */ RIS_DEFAULT,
    /* 01 */ RIS_EMPTY,
    /* 02 */ RIS_ENERGY_TANK,
    /* 03 */ RIS_MISSILE_TANK,
    /* 04 */ RIS_SUPER_MISSILE_TANK,
    /* 05 */ RIS_POWER_BOMB_TANK,
    /* 06 */ RIS_MAIN_MISSILES,
    /* 07 */ RIS_MAIN_SUPER_MISSILES,
    /* 08 */ RIS_MAIN_POWER_BOMBS,
    /* 09 */ RIS_LONG_BEAM,
    /* 10 */ RIS_CHARGE_BEAM,
    /* 11 */ RIS_ICE_BEAM,
    /* 12 */ RIS_WAVE_BEAM,
    /* 13 */ RIS_PLASMA_BEAM,
    /* 14 */ RIS_BOMBS,
    /* 15 */ RIS_VARIA_SUIT,
    /* 16 */ RIS_GRAVITY_SUIT,
    /* 17 */ RIS_MORPH_BALL,
    /* 18 */ RIS_SPEED_BOOSTER,
    /* 19 */ RIS_HI_JUMP,
    /* 20 */ RIS_SCREW_ATTACK,
    /* 21 */ RIS_SPACE_JUMP,
    /* 22 */ RIS_POWER_GRIP,
    /* 23 */ RIS_SPRING_BALL,
    /* 24 */ RIS_WALL_JUMP,
    /* 25 */ RIS_INF_BOMB_JUMP,
    /* 26 */ RIS_FULLY_POWERED,
    /* 27 */ RIS_ZIPLINES,
    /* 28 */ RIS_ANONYMOUS,
    /* 29 */ RIS_SHINY_MISSILE_TANK,
    /* 30 */ RIS_SHINY_SUPER_MISSILE_TANK,
    /* 31 */ RIS_SHINY_POWER_BOMB_TANK,
};

MAKE_ENUM(u8, RandoItemJingle) {
    /* 0 */ RIJ_DEFAULT,
    /* 1 */ RIJ_MINOR,
    /* 2 */ RIJ_MAJOR,
    /* 3 */ RIJ_UNKNOWN,
    /* 4 */ RIJ_FULLY_POWERED,
};

MAKE_ENUM(u8, RandoGoal) {
    /* 0 */ GOAL_MOTHER_BRAIN,
    /* 1 */ GOAL_MECHA_RIDLEY,
    /* 2 */ GOAL_INFANT_METROIDS
};

MAKE_ENUM(u8, DifficultyOptions) {
    /* 0 */ DIFF_OPT_UNCHANGED,
    /* 1 */ DIFF_OPT_ALL,
    /* 2 */ DIFF_OPT_EASY_NORMAL,
    /* 3 */ DIFF_OPT_HARD
};

#endif // RANDOMIZER_CONSTANTS_H
