#ifndef RANDOMIZER_CONSTANTS_H
#define RANDOMIZER_CONSTANTS_H

#include "macros.h"

#define MINOR_LOCATION_COUNT 86

#define MAX_ENERGY_CAPACITY 1299
#define MAX_MISSILE_CAPACITY 999
#define MAX_SUPER_MISSILE_CAPACITY 99
#define MAX_POWER_BOMB_CAPACITY 99

MAKE_ENUM(u8, ItemSource)
{
    /* 00 */ ITEM_SOURCE_LONG_BEAM,
    /* 01 */ ITEM_SOURCE_CHARGE_BEAM,
    /* 02 */ ITEM_SOURCE_ICE_BEAM,
    /* 03 */ ITEM_SOURCE_WAVE_BEAM,
    /* 04 */ ITEM_SOURCE_PLASMA_BEAM,
    /* 05 */ ITEM_SOURCE_BOMBS,
    /* 06 */ ITEM_SOURCE_VARIA_SUIT,
    /* 07 */ ITEM_SOURCE_GRAVITY_SUIT,
    /* 08 */ ITEM_SOURCE_MORPH_BALL,
    /* 09 */ ITEM_SOURCE_SPEED_BOOSTER,
    /* 10 */ ITEM_SOURCE_HI_JUMP,
    /* 11 */ ITEM_SOURCE_SCREW_ATTACK,
    /* 12 */ ITEM_SOURCE_SPACE_JUMP,
    /* 13 */ ITEM_SOURCE_POWER_GRIP,
    /* 14 */ ITEM_SOURCE_FULLY_POWERED,
    /* 15 */ ITEM_SOURCE_ZIPLINES,

    ITEM_SOURCE_COUNT
};

MAKE_ENUM(u8, RandoItemType) {
    /* 00 */ RIT_NONE,
    /* 01 */ RIT_ENERGY_TANK,
    /* 02 */ RIT_MISSILE_TANK,
    /* 03 */ RIT_SUPER_MISSILE_TANK,
    /* 04 */ RIT_POWER_BOMB_TANK,
    /* 05 */ RIT_LONG_BEAM,
    /* 06 */ RIT_CHARGE_BEAM,
    /* 07 */ RIT_ICE_BEAM,
    /* 08 */ RIT_WAVE_BEAM,
    /* 09 */ RIT_PLASMA_BEAM,
    /* 10 */ RIT_BOMBS,
    /* 11 */ RIT_VARIA_SUIT,
    /* 12 */ RIT_GRAVITY_SUIT,
    /* 13 */ RIT_MORPH_BALL,
    /* 14 */ RIT_SPEED_BOOSTER,
    /* 15 */ RIT_HI_JUMP,
    /* 16 */ RIT_SCREW_ATTACK,
    /* 17 */ RIT_SPACE_JUMP,
    /* 18 */ RIT_POWER_GRIP,
    /* 19 */ RIT_FULLY_POWERED,
    /* 20 */ RIT_ZIPLINES,
    /* 21 */ RIT_ICE_TRAP,
};

MAKE_ENUM(u8, RandoItemSprite) {
    /* 00 */ RIS_DEFAULT,
    /* 01 */ RIS_EMPTY,
    /* 02 */ RIS_ENERGY_TANK,
    /* 03 */ RIS_MISSILE_TANK,
    /* 04 */ RIS_SUPER_MISSILE_TANK,
    /* 05 */ RIS_POWER_BOMB_TANK,
    /* 06 */ RIS_LONG_BEAM,
    /* 07 */ RIS_CHARGE_BEAM,
    /* 08 */ RIS_ICE_BEAM,
    /* 09 */ RIS_WAVE_BEAM,
    /* 10 */ RIS_PLASMA_BEAM,
    /* 11 */ RIS_BOMBS,
    /* 12 */ RIS_VARIA_SUIT,
    /* 13 */ RIS_GRAVITY_SUIT,
    /* 14 */ RIS_MORPH_BALL,
    /* 15 */ RIS_SPEED_BOOSTER,
    /* 16 */ RIS_HI_JUMP,
    /* 17 */ RIS_SCREW_ATTACK,
    /* 18 */ RIS_SPACE_JUMP,
    /* 19 */ RIS_POWER_GRIP,
    /* 20 */ RIS_FULLY_POWERED,
    /* 21 */ RIS_ZIPLINES,
    /* 22 */ RIS_ANONYMOUS,
    /* 23 */ RIS_SHINY_MISSILE_TANK,
    /* 24 */ RIS_SHINY_POWER_BOMB_TANK,
};

MAKE_ENUM(u8, RandoItemJingle) {
    /* 0 */ RIJ_DEFAULT,
    /* 1 */ RIJ_MINOR,
    /* 2 */ RIJ_MAJOR,
    /* 3 */ RIJ_UNKNOWN,
    /* 4 */ RIJ_FULLY_POWERED,
};

MAKE_ENUM(u8, DifficultyOptions) {
    /* 0 */ DIFF_OPT_UNCHANGED,
    /* 1 */ DIFF_OPT_ALL,
    /* 2 */ DIFF_OPT_EASY_NORMAL,
    /* 3 */ DIFF_OPT_HARD
};

#endif // RANDOMIZER_CONSTANTS_H
